version: '3.8'

services:
    dev:
      build: .
      command: npm start
      image: express-typescript
      volumes:
        - .:/usr/app/
        - /usr/app/node_modules
      ports:
        - "3000:3000"